"""create interactions table

Revision ID: a4091810dc8e
Revises: 
Create Date: 2026-07-14 22:59:53.682162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4091810dc8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hcp_name', sa.String(length=255), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('interaction_date', sa.Date(), nullable=False),
    sa.Column('interaction_time', sa.Time(), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('topics_discussed', sa.Text(), nullable=True),
    sa.Column('materials_shared', sa.Text(), nullable=True),
    sa.Column('samples_distributed', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('outcomes', sa.Text(), nullable=True),
    sa.Column('follow_up_actions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###
